---
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 56
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
