language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
dist: trusty
branches:
  only:
  - master
  - stable
env:
  - FEDORA_VERSION="3.8.1"
before_script:
  - composer install
  - $TRAVIS_BUILD_DIR/tests/scripts/travis_setup.sh
script:
  - composer test
after_success:
  - bash <(curl -s https://codecov.io/bash)
